- name: Linux VM patching 
  hosts: web 
  become: yes 
  tasks: 
    - name: Update all packages 
      dnf: 
        name: "*" 
        state: latest 
 
    - name: Check reboot requirement 
      command: needs-restarting -r 
      register: reboot_required 
      failed_when: false 
      changed_when: false 
 
    - name: Reboot if required 
      reboot: 
        reboot_timeout: 600 
      when: reboot_required.rc == 1
